### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by DarrickFauvel** [DarrickFauvel/hangman-js#1]
#### Description
HTML, CSS, and JavaScript code can be cleaned up.

#### Tasks
- [ ] Simplify HTML and CSS classes and ID's
- [x] Use semantic elements
- [ ] Organize CSS
- [ ] Convert JS functions to arrow functions
- [ ] Add a footer
